In [1]:
import numpy as np
from datascience import *

#path_data = '../../assets/data/'

In [3]:
! ls ../../assets/data/

actors.csv	    galton.csv			   observed_outcomes.csv
airline_ontime.csv  galton_subset.csv		   potential_outcomes.csv
all-lprs.csv.gz     grades_and_piazza.csv	   roulette_wheel.csv
anscombe.csv	    heights.csv			   san_francisco_2015.csv
baby.csv	    hodgkins.csv		   san_francisco_2019.csv
banknote.csv	    house.csv			   sat2014.csv
birds.csv	    hybrid.csv			   scores_by_section.csv
birth_time.csv	    hybrid_reg.csv		   shotput.csv
breast-cancer.csv   income_small.csv		   sons_heights.csv
bta.csv		    IV.csv			   station.csv
children_raw.csv    kaiser_ethnicity_children.csv  top_movies_2017.csv
ckd.csv		    kaiser_ethnicity_everyone.csv  top_movies.csv
cones.csv	    little_women.csv		   trip.csv
couples.csv	    married_couples.csv		   unfair_flips.csv
deflategate.csv     minard.csv			   united_summer2015.csv
dugongs.csv	    movies_by_year.csv		   usa_ca_2014.csv
educ_inc.csv	    nba2013.csv			   usa_ca_2019.csv
everyone_raw.csv    nba_salaries.csv		   us_women.csv
faithful.csv	    nc

# 05. Sequences

Values can be grouped together into collections, which allows programmers to organize those values and refer to all of them with a single name. By grouping values together, we can write code that performs a computation on many pieces of data at once.

Calling the function `make_array` on several values places them into an *array*, which is a kind of sequential collection. Below, we collect four different temperatures into an array called `highs`. These are the [estimated average daily high temperatures](http://berkeleyearth.lbl.gov/regions/global-land) over all land on Earth (in degrees Celsius) for the decades surrounding 1850, 1900, 1950, and 2000, respectively, expressed as deviations from the average absolute high temperature between 1951 and 1980, which was 14.48 degrees.

In [4]:
#make_array?

In [7]:
baseline_high = 14.48

highs = make_array ( baseline_high - 0.880, baseline_high - 0.093,
                     baseline_high + 0.105, baseline_high + 0.684 )

highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [8]:
xhighs = np.array([ baseline_high - 0.880, baseline_high - 0.093,
                   baseline_high + 0.105, baseline_high + 0.684 ])

xhighs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [9]:
print ( highs.shape )

(4,)


In [10]:
print ( highs.size )

4


In [12]:
print ( np.info(highs) ) 

class:  ndarray
shape:  (4,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x560d6647f2d0
byteorder:  little
byteswap:  False
type: float64
None


Collections allow us to pass multiple values into a function using a single name. For instance, the `sum` function computes the sum of all values in a collection, and the `len` function computes its length. (That's the number of values we put in it.) Using them together, we can compute the average of a collection.

In [13]:
sum(highs)/len(highs)

14.434000000000001

The complete chart of daily high and low temperatures appears below. 

<h2>Mean of Daily High Temperature</h2>

![Mean of Daily High Temperature](../../images/global-land-TMAX-Trend.png)

<h2>Mean of Daily Low Temperature</h2>

![Mean of Daily Low Temperature](../../images/global-land-TMIN-Trend.png)

In [14]:
#! ls ../../images/

# 05.1. Arrays

While there are many kinds of collections in Python, we will work primarily with arrays in this class. We've already seen that the `make_array` function can be used to create arrays of numbers.

Arrays can also contain strings or other types of values, but a single array can only contain a single kind of data. (It usually doesn't make sense to group together unlike data anyway.)  For example:

In [15]:
english_parts_of_speech = make_array (
    "noun", "pronoun", "verb", "adverb", 
    "adjective", "conjunction", "preposition", 
    "interjection")

english_parts_of_speech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'],
      dtype='<U12')

Returning to the temperature data, we create arrays of average daily [high temperatures](http://berkeleyearth.lbl.gov/auto/Regional/TMAX/Text/global-land-TMAX-Trend.txt) for the decades surrounding 1850, 1900, 1950, and 2000.

In [16]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684)
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

Arrays can be used in arithmetic expressions to compute over their contents. When an array is combined with a single number, that number is combined with each element of the array. Therefore, we can convert all of these temperatures to Fahrenheit by writing the familiar conversion formula.

In [17]:
(9/5) * highs + 32

array([ 56.48  ,  57.8966,  58.253 ,  59.2952])

![array arithmetic](../../images/array_arithmetic.png)

In [18]:
#! ls ../../images/

Arrays also have *methods*, which are functions that operate on the array values. The `mean` of a collection of numbers is its average value: the sum divided by the length. Each pair of parentheses in the examples below is part of a call expression; it's calling a function with no arguments to perform a computation on the array called `highs`.

In [19]:
highs.size

4

In [20]:
highs.sum()

57.736000000000004

In [21]:
highs.mean()

14.434000000000001

## Functions on Arrays
The `numpy` package, abbreviated `np` in programs, provides Python programmers with convenient and powerful functions for creating and manipulating arrays.

For example, the `diff` function computes the difference between each adjacent pair of elements in an array. The first element of the `diff` is the second element minus the first. 

In [22]:
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [23]:
np.diff(highs)

array([ 0.787,  0.198,  0.579])

In [24]:
dh = np.diff(highs)

#
# Let's check what was going on ...
for i in range(highs.size-1):
    print ( i, highs[i+1] - highs[i],  dh[i] ) 

0 0.787 0.787
1 0.198 0.198
2 0.579 0.579


The [full Numpy reference](http://docs.scipy.org/doc/numpy/reference/) lists these functions exhaustively, but only a small subset are used commonly for data processing applications. These are grouped into different packages within `np`. Learning this vocabulary is an important part of learning the Python language, so refer back to this list often as you work through examples and problems.

However, you **don't need to memorize these**.  Use this as a reference.

Each of these functions takes an array as an argument and returns a single value.

| **Function**       | Description                                                          |
|--------------------|----------------------------------------------------------------------|
| `np.prod`          | Multiply all elements together                                       |
| `np.sum`           | Add all elements together                                            |
| `np.all`           | Test whether all elements are true values (non-zero numbers are true)|
| `np.any`           | Test whether any elements are true values (non-zero numbers are true)|
| `np.count_nonzero` | Count the number of non-zero elements                                |

Each of these functions takes an array as an argument and returns an array of values.

| **Function**       | Description                                                          |
|--------------------|----------------------------------------------------------------------|
| `np.diff`          | Difference between adjacent elements                                 |
| `np.round`         | Round each number to the nearest integer (whole number)              |
| `np.cumprod`       | A cumulative product: for each element, multiply all elements so far |
| `np.cumsum`        | A cumulative sum: for each element, add all elements so far          |
| `np.exp`           | Exponentiate each element                                            |
| `np.log`           | Take the natural logarithm of each element                           |
| `np.sqrt`          | Take the square root of each element                                 |
| `np.sort`          | Sort the elements                                                    |

Each of these functions takes an array of strings and returns an array.

| **Function**        | **Description**                                              |
|---------------------|--------------------------------------------------------------|
| `np.char.lower`     | Lowercase each element                                       |
| `np.char.upper`     | Uppercase each element                                       |
| `np.char.strip`     | Remove spaces at the beginning or end of each element        |
| `np.char.isalpha`   | Whether each element is only letters (no numbers or symbols) |
| `np.char.isnumeric` | Whether each element is only numeric (no letters)  

Each of these functions takes both an array of strings and a *search string*; each returns an array.

| **Function**         | **Description**                                                                  |
|----------------------|----------------------------------------------------------------------------------|
| `np.char.count`      | Count the number of times a search string appears among the elements of an array |
| `np.char.find`       | The position within each element that a search string is found first             |
| `np.char.rfind`      | The position within each element that a search string is found last              |
| `np.char.startswith` | Whether each element starts with the search string  



In [25]:
highs.prod()

43274.231214608

In [26]:
#
# Let's check what was going on ...

pr = 1 
for i in range(highs.size):
    pr = pr * highs[i]
#
print ( "highs.prod() = ", pr)

highs.prod() =  43274.2312146


In [27]:
pr

43274.231214608

In [28]:
highs.cumsum()

array([ 13.6  ,  27.987,  42.572,  57.736])

In [29]:
#
# Let's check what was going on ...

cs = np.zeros( highs.size )
cs[0] = highs[0]

for i in range(1,highs.size):
    cs[i] = cs[i-1] + highs[i]  
#

print ( "highs.cumsum() = ", cs )

highs.cumsum() =  [ 13.6    27.987  42.572  57.736]


In [30]:
highs.cumprod()

array([  1.36000000e+01,   1.95663200e+02,   2.85374777e+03,
         4.32742312e+04])

In [31]:
#
# Let's check what was going on ...

cp = np.ones( highs.size )
cp[0] = highs[0]

for i in range(1,highs.size):
    cp[i] = cp[i-1] * highs[i]  
#

print ( "highs.cumprod() = ", cp )

highs.cumprod() =  [  1.36000000e+01   1.95663200e+02   2.85374777e+03   4.32742312e+04]


# 05.2. Ranges

A *range* is an array of numbers in increasing or decreasing order, each separated by a regular interval. 
Ranges are useful in a surprisingly large number of situations, so it's worthwhile to learn about them.

Ranges are defined  using the `np.arange` function, which takes either one, two, or three arguments: a start, and end, and a 'step'.

If you pass one argument to `np.arange`, this becomes the `end` value, with `start=0`, `step=1` assumed.  Two arguments give the `start` and `end` with `step=1` assumed.  Three arguments give the `start`, `end` and `step` explicitly.

A range always includes its `start` value, but does not include its `end` value.  It counts up by `step`, and it stops before it gets to the `end`.

    np.arange(end): An array starting with 0 of increasing consecutive integers, stopping before end.

In [32]:
np.arange(5)

array([0, 1, 2, 3, 4])

Notice how the array starts at 0 and goes only up to 4, not to the end value of 5.


    np.arange(start, end): An array of consecutive increasing integers from start, stopping before end.

In [33]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])


    np.arange(start, end, step): A range with a difference of step between each pair of consecutive values, starting from start and stopping before end.

In [34]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

This array starts at 3, then takes a step of 5 to get to 8, then another step of 5 to get to 13, and so on.

When you specify a step, the start, end, and step can all be either positive or negative and may be whole numbers or fractions. 

In [35]:
np.arange(1.5, -2, -0.5)

array([ 1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5])

## Example: Leibniz's formula for $\pi$

The great German mathematician and philosopher [Gottfried Wilhelm Leibniz](https://en.wikipedia.org/wiki/Gottfried_Wilhelm_Leibniz) 
(1646 - 1716) discovered a wonderful formula for $\pi$ as an infinite sum of simple fractions. The formula is

$$\pi = 4 \cdot \left(1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} - \frac{1}{11} + \dots\right)$$

Though some math is needed to establish this, we can use arrays to convince ourselves that the formula works. Let's calculate the first 5000 terms of Leibniz's infinite sum and see if it is close to $\pi$.

$$4 \cdot \left(1 - \frac{1}{3} + \frac{1}{5} - \frac{1}{7} + \frac{1}{9} - \frac{1}{11} + \dots - \frac{1}{9999} \right)$$

We will calculate this finite sum by adding all the positive terms first and then subtracting the sum of all the negative terms [[1]](#footnotes):

$$4 \cdot \left( \left(1 + \frac{1}{5} + \frac{1}{9} + \dots + \frac{1}{9997} \right) - \left(\frac{1}{3} + \frac{1}{7} + \frac{1}{11} + \dots + \frac{1}{9999} \right) \right)$$

The positive terms in the sum have 1, 5, 9, and so on in the denominators. The array `by_four_to_20` contains these numbers up to 17:

In [36]:
by_four_to_20 = np.arange(1, 20, 4)
by_four_to_20

array([ 1,  5,  9, 13, 17])

To get an accurate approximation to $\pi$, we'll use the much longer array `positive_term_denominators`.

In [37]:
positive_term_denominators = np.arange(1, 10000, 4)
positive_term_denominators

array([   1,    5,    9, ..., 9989, 9993, 9997])

The positive terms we actually want to add together are just 1 over these denominators:

In [38]:
positive_terms = 1 / positive_term_denominators
positive_terms

array([  1.00000000e+00,   2.00000000e-01,   1.11111111e-01, ...,
         1.00110121e-04,   1.00070049e-04,   1.00030009e-04])

The negative terms have 3, 7, 11, and so on on in their denominators. This array is just 2 added to `positive_term_denominators`.

In [39]:
negative_terms = 1 / (positive_term_denominators + 2)
negative_terms

array([  3.33333333e-01,   1.42857143e-01,   9.09090909e-02, ...,
         1.00090081e-04,   1.00050025e-04,   1.00010001e-04])

The overall sum is

In [40]:
pi1 = 4 * ( sum(positive_terms) - sum(negative_terms) )
pi1 

3.1413926535917955

This is very close to $\pi = 3.14159\dots$. Leibniz's formula is looking good!

In [41]:
print ( "| pi.exact - pi.approx | = %11.4e" %  abs( np.pi - pi1 ) )  

| pi.exact - pi.approx | =  2.0000e-04


<a id='footnotes'></a>
## Footnotes
[1] Surprisingly, when we add  *infinitely* many positive and negative fractions, the order can matter! But our approximation to $\pi$ uses only a large finite number of fractions, so it's okay to add the terms in any convenient order.

Again

In [47]:
n = 100000000

positive_term_denominators = np.arange(1, n, 4)

positive_terms = 1 / positive_term_denominators
negative_terms = 1 / (positive_term_denominators + 2)

pi2 = 4 * ( sum(positive_terms) - sum(negative_terms) )

print ( "| pi.exact - pi.approx | = %11.4e" %  abs( np.pi - pi2 ) )  

| pi.exact - pi.approx | =  2.0006e-08


# 05.3. More on Arrays
It's often necessary to compute something that involves data from more than one array. If two arrays are of the same size, Python makes it easy to do calculations involving both arrays.

For our first example, we return once more to the temperature data.  This time, we create arrays of average daily [high](http://berkeleyearth.lbl.gov/auto/Regional/TMAX/Text/global-land-TMAX-Trend.txt) and [low](http://berkeleyearth.lbl.gov/auto/Regional/TMIN/Text/global-land-TMIN-Trend.txt) temperatures for the decades surrounding 1850, 1900, 1950, and 2000.

In [48]:
baseline_high = 14.48
highs = make_array(baseline_high - 0.880, 
                   baseline_high - 0.093,
                   baseline_high + 0.105, 
                   baseline_high + 0.684)
highs

array([ 13.6  ,  14.387,  14.585,  15.164])

In [49]:
baseline_low = 3.00
lows = make_array(baseline_low - 0.872, baseline_low - 0.629,
                  baseline_low - 0.126, baseline_low + 0.728)
lows

array([ 2.128,  2.371,  2.874,  3.728])

Suppose we'd like to compute the average daily *range* of temperatures for each decade.  That is, we want to subtract the average daily high in the 1850s from the average daily low in the 1850s, and the same for each other decade.

We could write this laboriously using `.item`:

In [50]:
make_array(
    highs.item(0) - lows.item(0),
    highs.item(1) - lows.item(1),
    highs.item(2) - lows.item(2),
    highs.item(3) - lows.item(3)
)

array([ 11.472,  12.016,  11.711,  11.436])

Is this better ?

In [51]:
make_array(
    highs[0] - lows[0],
    highs[1] - lows[1],
    highs[2] - lows[2],
    highs[3] - lows[3]
)

array([ 11.472,  12.016,  11.711,  11.436])

But, this best solution may be the following 

As when we converted an array of temperatures from Celsius to Fahrenheit, Python provides a much cleaner way to write this:

In [52]:
highs - lows

array([ 11.472,  12.016,  11.711,  11.436])

![array subtraction](../../images/array_subtraction.png)

What we've seen in these examples are special cases of a general feature of arrays.

## Elementwise arithmetic on pairs of numerical arrays
If an arithmetic operator acts on two arrays of the same size, then the operation is performed on each corresponding pair of elements in the two arrays. The final result is an array. 

For example, if `array1` and `array2` have the same number of elements, then the value of `array1 * array2` is an array. Its first element is the first element of `array1` times the first element of `array2`, its second element is the second element of `array1` times the second element of `array2`, and so on.

This is a product of "even/odd" fractions. Let's use arrays to multiply a million of them, and see if the product is close to $\pi$.

Remember that multiplication can done in any order [[1]](#footnotes), so we can readjust our calculation to:

$$\pi \approx 2 \cdot \left( \frac{2}{1} \cdot \frac{4}{3} \cdot \frac{6}{5} \cdots \frac{1,000,000}{999999} \right) \cdot \left( \frac{2}{3} \cdot \frac{4}{5} \cdot \frac{6}{7} \cdots \frac{1,000,000}{1,000,001} \right)$$

We're now ready to do the calculation. We start by creating an array of even numbers 2, 4, 6, and so on upto 1,000,000. Then we create two lists of odd numbers: 1, 3, 5, 7, ... upto 999,999, and 3, 5, 7, ... upto 1,000,001.

In [53]:
even = np.arange(2, 1000001, 2)
one_below_even = even - 1
one_above_even = even + 1

In [54]:
even

array([      2,       4,       6, ...,  999996,  999998, 1000000])

In [55]:
one_below_even

array([     1,      3,      5, ..., 999995, 999997, 999999])

In [56]:
one_above_even

array([      3,       5,       7, ...,  999997,  999999, 1000001])

Remember that `np.prod` multiplies all the elements of an array together. Now we can calculate Wallis' product, to a good approximation.

In [57]:
pi3 = 2 * np.prod(even/one_below_even) * np.prod(even/one_above_even)
pi3 

3.1415910827951143

In [58]:
print ( "| pi.exact - pi.approx | = %11.4e" %  abs( np.pi - pi3 ) )  

| pi.exact - pi.approx | =  1.5708e-06


That's $\pi$ correct to five decimal places.  Wallis clearly came up with a great formula.

<a id='footnotes'></a>
## Footnotes
[1] As we saw in the example about Leibniz's formula, when we add  *infinitely* many fractions, the order can matter. The same is true with multiplying fractions, as we are doing here. But our approximation to $\pi$ uses only a large finite number of fractions, so it's okay to multiply the terms in any convenient order.

# Exercises: 


1. Approximate numerically $\pi = 3.141592653589 \ldots $ from the Nilakantha's series: ([source](https://en.wikipedia.org/wiki/Pi)) 
\begin{eqnarray}
    \pi 
    = 
    3 
    +
    \frac{4}{ 2 \cdot 3 \cdot 4 }
    -
    \frac{4}{ 4 \cdot 5 \cdot 6 }
    +
    \frac{4}{ 6 \cdot 7 \cdot 8 }
    -
    \ldots
\end{eqnarray}

2. Approximate $e = 2.7182818284 \ldots $ numerically from 
\begin{eqnarray}
    e
    = 
    \sum_{ k = 0 }^{ \infty }
    \frac{
        1
    }{
        k!
    }
    =
    1 
    + 
    \frac{1}{1}
    +
    \frac{1 }{ 1 \cdot 2 }
    +
    \frac{1 }{ 1 \cdot 2 \cdot 3 }
    +
    \frac{1 }{ 1 \cdot 2 \cdot 3 \cdot 4 }
    +
    \ldots 
\end{eqnarray}

3. Can you approximate and plot the cumulative distribution function (CDF) of the standard normal distribution ?
\begin{eqnarray}
    \Phi(x)
    =
    \frac{ 1 }{ \sqrt{ 2 \pi } }
    \int_{ -\infty }^{ x }
    \mathrm{e}^{ -t^2 / 2 }
    \mathrm{d} t
\end{eqnarray}
Suppose that we are interested in $\Phi(x_k)$ for $x_k \in [-10,10]$ with the uniform step size 
$\Delta x = |x_k - x_{k-1}| = 0.2 $. 

Hint: Put 
$$
    x_0 = -10 
    ,\quad 
    x_{N} = 10
    ,
    \quad 
    \Delta x = \frac{ x_{N} - x_{0} }{ N } = 0.2 
    ,
    \quad 
    N = ???
    ,\quad 
    x_{k} = x_{0} + k \Delta x
    ,
    \quad 
    k = \overline{0,N}
$$
and 
$ f(t) = \mathrm{e}^{ -t^2 / 2 } $.
Since 
$ f(x)  \simeq 0 $ for $x \le x_0 $,
you can approximate $\Phi(x_k)$ by
$$
    \Phi(x_k)
    \sqrt{ 2 \pi }
    =
    \int_{ -\infty }^{ x_{k} }
    f(t) 
    \mathrm{d} t
    \simeq
    \int_{ x_0 }^{ x_{k} }
    f(t) 
    \mathrm{d} t
    =
    \sum_{j = 1}^{k}
    \int_{ x_{j-1} }^{ x_{j} }
    f(t) 
    \mathrm{d} t
,
$$
where you can evaluate $\int_{ x_{j-1} }^{ x_{j} }
    f(t) 
    \mathrm{d} t$
using one of the following methods.    

(a) the trapezoidal rule
$$
    \quad 
    \int_{ x_{j-1} }^{ x_{j} }
    f(t)
    \mathrm{d} t
    \simeq
\;
    \Delta x 
    \frac{
        f(x_{j}) + f(x_{j-1})
    }{ 2}
.
$$
Or, 

(b) the midpoint rule
$$
    \quad 
    \int_{ x_{j-1}  }^{ x_{j}  }
    f(t)
    \mathrm{d} t
    \simeq
\;    
    \Delta x \;
     f \left( \frac{ x_{j-1} + x_{j} }{2} \right)
.
$$

After that, you can validate your approximation from the identity: ([source](https://en.wikipedia.org/wiki/Normal_distribution))
$$
    \Phi (x) =
    \frac{1}{2}
    \left( 
        1 + \mathrm{erf} \left( x / \sqrt{2} \right)
    \right)
$$
Here the error function $\mathrm{erf}(x) $ can be obtain from 
[scipy.special.erf](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.erf.html).